DROPBOX=~/.dropbox_data/Dropbox/
WIKI=~/.dropbox_data/Dropbox/wiki/
FINANZAS=~/.dropbox_data/Dropbox/wiki/finanzas/
DEV=~/develop
CDS=~/develop/cds
CHRISTIAN=~/develop/cds/christian
SIMBIOTICA=~/develop/simbiotica
MYTAPP_MOBILE=/Users/arturovolpe/develop/cds/mytapp/ionic-test
MYTAPP=/Users/arturovolpe/develop/cds/mytapp
TESAKA="/Users/arturovolpe/Library/Application Support/Tesaka/db"
SIMBIOTICA_COBRANZA=~/develop/simbiotica/cobranza-movil
FIELCO=~/develop/cds/fielco
SGM=~/develop/simbiotica/barcelona/tag
YODONO=~/develop/simbiotica/yodono/app
BOCADEURNA=~/develop/personal/bocadeurnapy
COTIZACION=~/develop/personal/cotizaciones
taxio=~/develop/cosmesoft/taxio
